---
- name: pepe
  hosts: all
  tasks:
    - template:
        src: template.j2
        dest: /path
    - service:
        name: apache
        action: restart
    - file:
        path: pepe


- name: test
  hosts: all
  action: touch pepe
  register: hola

- name: test2
  copya
